#server:
#  port: 31001
#spring:
#  application:
#    name: xc-service-manage-cms
#  data:
#    mongodb:
#      uri:  mongodb://root:123@localhost:27017
#      database: xc_cms

server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri:  mongodb://localhost:27017
      database: StudyOnLine